title: Calouera Store
email: vendas@calouera.com
description: >- # this means to ignore newlines until "baseurl:"
  All You Need!
url: "https://calouera.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate-v2
  - jekyll-email-protect
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics

autopages:
  enabled: true
  collections:
    enabled: true

pagination:
  enabled: true
  per_page: 15
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - bower_components
  - admin/index.js
  - webpack.config.js
  - package.json
  - README.md

sass:
  sass_dir: assets/_sass
  style: compressed

collections:
  infantil:
  masculino:
  femenino:
  fitness:
  smartphone:

image:
logo: /assets/img/logo.svg
color: "#820333"

jekyll_analytics: 
  GoogleAnalytics:
    id: UA-112487267-1
    anonymizeIp: false