backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: master

media_folder: "assets/img/uploads"

collections:
  - name: "produtos"
    label: "produtos"
    folder: "_produtos"
    create: true
    fields:
      - {label: "Nome do Produto", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - label: Categoria
        name: family
        widget: select
        options: ["braceletes", "carteiras", "cintos", "chapeus", "gravatas", "relogios", "pastas", "oculos", "meias"]
